steps:
- name: gcr.io/kaniko-project/executor:latest
  args:
  - --cache=true
  - --cache-ttl=168h
  - --destination=us-central1-docker.pkg.dev/clp-cloudpack-ci-dev2-section/kok-hashimoto-cloudrun-go-cicd/web:latest
