steps:
- name: golang:1.20
  id: go-test
  waitFor: ['-']
  entrypoint: go
  args:
  - test
  - ./...
- name: golang:1.20
  id: staticcheck
  waitFor: ['-']
  script: |
    go install honnef.co/go/tools/cmd/staticcheck@latest
    staticcheck ./...
- name: hadolint/hadolint:latest-debian
  id: hadolint
  waitFor: ['-']
  entrypoint: hadolint
  args:
  - --ignore=DL3006
  - --ignore=DL3007
  - Dockerfile
- name: gcr.io/kaniko-project/executor:latest
  id: docker-build
  waitFor:
    - go-test
    - staticcheck
    - hadolint
  args:
  - --cache=true
  - --cache-ttl=168h
  - --destination=us-central1-docker.pkg.dev/clp-cloudpack-ci-dev2-section/kok-hashimoto-cloudrun-go-cicd/web:$COMMIT_SHA
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  waitFor:
    - docker-build
  entrypoint: gcloud
  args:
  - run
  - deploy
  - kok-hashimoto-cloudrun-go-cicd
  - --allow-unauthenticated
  - --execution-environment=gen2
  - --image=us-central1-docker.pkg.dev/clp-cloudpack-ci-dev2-section/kok-hashimoto-cloudrun-go-cicd/web:$COMMIT_SHA
  - --region=us-central1
